// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgb_JzJnsTPwEr0FdmYjrh6MUk4pzy_Y0',
    appId: '1:484488690977:web:36c28231f83de05755d260',
    messagingSenderId: '484488690977',
    projectId: 'fakrni-656da',
    authDomain: 'fakrni-656da.firebaseapp.com',
    storageBucket: 'fakrni-656da.firebasestorage.app',
    measurementId: 'G-MN1RYLGN40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUdJKvjKAdid3pWeaKpQ9KpibyJUqTc7U',
    appId: '1:484488690977:android:fd49563c0706b79855d260',
    messagingSenderId: '484488690977',
    projectId: 'fakrni-656da',
    storageBucket: 'fakrni-656da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPX3P_rYjGkgTXs_ip8FSwenSdrIrz9I',
    appId: '1:484488690977:ios:f94ba08900431e3b55d260',
    messagingSenderId: '484488690977',
    projectId: 'fakrni-656da',
    storageBucket: 'fakrni-656da.firebasestorage.app',
    iosClientId: '484488690977-inp81cmk6ov6fkpn8260a89initgn79j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakrni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiPX3P_rYjGkgTXs_ip8FSwenSdrIrz9I',
    appId: '1:484488690977:ios:f94ba08900431e3b55d260',
    messagingSenderId: '484488690977',
    projectId: 'fakrni-656da',
    storageBucket: 'fakrni-656da.firebasestorage.app',
    iosClientId: '484488690977-inp81cmk6ov6fkpn8260a89initgn79j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakrni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgb_JzJnsTPwEr0FdmYjrh6MUk4pzy_Y0',
    appId: '1:484488690977:web:8457e8a6900b54ae55d260',
    messagingSenderId: '484488690977',
    projectId: 'fakrni-656da',
    authDomain: 'fakrni-656da.firebaseapp.com',
    storageBucket: 'fakrni-656da.firebasestorage.app',
    measurementId: 'G-NM8SFC5K4P',
  );
}
